# Site settings
name: Ahmad Jarir A.
title: Ahmad Jarir A. | Backend Software Engineer
description: ''
url: https://aja-x.github.io/
baseurl: ''
email: aja-x.soft.en@gmail.com
cover: https://aja-x.github.io/img/og.png
logo: https://aja-x.github.io/img/emojis/ideogram.ico
resume: https://aja-x.github.io/resume.pdf
social:
  - title: email
    url: mailto:aja-x.soft.en@gmail.com
  - title: github
    url: https://github.com/aja-x
  - title: gitlab
    url: https://gitlab.com/aja-x
  - title: linkedin
    url: https://www.linkedin.com/in/ahmad-jarir

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
